"""baseline_mysql_schema

Revision ID: 0001
Revises:
Create Date: 2026-08-06 01:29:20.864086

Single squashed baseline replacing the 21 Postgres-authored migrations from
the original ch-tech repo. This is a deliberate one-time exception to
DATABASE_MIGRATIONS.md's "una responsabilidad por migración" rule: the data
scope for this migration is structure-only (no production rows to replay),
so there's nothing gained by recreating incremental history that exists
purely to work around Postgres quirks (e.g. the dropped pg_trgm index).
Generated via `alembic revision --autogenerate` against a live, empty
MySQL 8.4 database — not hand-written — so it is guaranteed driftless
against app/models/*.py at the time it was created (verified by `alembic
check`, see docs/DATABASE_MIGRATIONS.md).
"""

import uuid
from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op

from app.db.types import GUID, UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_service_lines_table = sa.table(
    "service_lines",
    sa.column("id", GUID()),
    sa.column("slug", sa.String()),
    sa.column("name", sa.String()),
    sa.column("description", sa.Text()),
    sa.column("icon", sa.Text()),
    sa.column("display_order", sa.Integer()),
    sa.column("created_at", UTCDateTime()),
    sa.column("updated_at", UTCDateTime()),
)

# VISION.md "Modelo de Negocio" — the five business lines, in the order
# documented there.
_BUSINESS_LINES = [
    ("software-engineering", "Software Engineering"),
    ("ai-automation", "AI & Automation"),
    ("digital-solutions", "Digital Solutions"),
    ("saas-products", "SaaS Products"),
    ("technology-consulting", "Technology Consulting"),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("logo", sa.Text(), nullable=True),
        sa.Column("industry", sa.String(length=150), nullable=True),
        sa.Column("website_url", sa.Text(), nullable=True),
        sa.Column("id", GUID(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "companies",
        sa.Column("legal_name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=150), nullable=False),
        sa.Column("tagline", sa.String(length=255), nullable=True),
        sa.Column("mission", sa.Text(), nullable=True),
        sa.Column("vision", sa.Text(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("social_links", sa.JSON(), nullable=True),
        sa.Column("id", GUID(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "partners",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("logo", sa.Text(), nullable=True),
        sa.Column("partnership_type", sa.String(length=100), nullable=True),
        sa.Column("website_url", sa.Text(), nullable=True),
        sa.Column("id", GUID(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "products",
        sa.Column("slug", sa.String(length=150), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("short_description", sa.Text(), nullable=True),
        sa.Column("full_description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("logo", sa.Text(), nullable=True),
        sa.Column("featured", sa.Boolean(), nullable=False),
        sa.Column("id", GUID(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('WAITLIST', 'BETA', 'LIVE')", name="ck_products_status"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_products_slug"), "products", ["slug"], unique=True)
    op.create_index(op.f("ix_products_status"), "products", ["status"], unique=False)
    op.create_table(
        "service_lines",
        sa.Column("slug", sa.String(length=150), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.Text(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("id", GUID(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_service_lines_slug"), "service_lines", ["slug"], unique=True
    )
    # Seeds the five CH-TECH V2 business lines (VISION.md) as catalog data —
    # DATABASE_MIGRATIONS.md allows "catálogos necesarios para el
    # funcionamiento" in a migration; this is exactly that, not business
    # content. Carried over verbatim from the original Postgres migration.
    now = datetime.now(UTC)
    op.bulk_insert(
        _service_lines_table,
        [
            {
                "id": uuid.uuid4(),
                "slug": slug,
                "name": name,
                "description": None,
                "icon": None,
                "display_order": order,
                "created_at": now,
                "updated_at": now,
            }
            for order, (slug, name) in enumerate(_BUSINESS_LINES)
        ],
    )
    op.create_table(
        "technologies",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("icon", sa.Text(), nullable=True),
        sa.Column("official_url", sa.Text(), nullable=True),
        sa.Column("id", GUID(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_technologies_name"), "technologies", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "email_lower",
            sa.String(length=255),
            sa.Computed("LOWER(email)", persisted=True),
            nullable=False,
        ),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login", UTCDateTime(), nullable=True),
        sa.Column("id", GUID(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint("role IN ('ADMIN')", name="ck_users_role"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("uq_users_email_lower", "users", ["email_lower"], unique=True)
    op.create_table(
        "articles",
        sa.Column("author_id", GUID(), nullable=False),
        sa.Column("slug", sa.String(length=150), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("cover_image", sa.Text(), nullable=True),
        sa.Column("reading_time", sa.Integer(), nullable=True),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("published_at", UTCDateTime(), nullable=True),
        sa.Column("id", GUID(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "NOT published OR published_at IS NOT NULL",
            name="ck_articles_published_requires_published_at",
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_articles_published"), "articles", ["published"], unique=False
    )
    op.create_index(op.f("ix_articles_slug"), "articles", ["slug"], unique=True)
    op.create_table(
        "contact_requests",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("company", sa.String(length=255), nullable=True),
        sa.Column("subject", sa.String(length=255), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "interested_service_line_id", GUID(), nullable=True
        ),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("id", GUID(), nullable=False),
        sa.CheckConstraint(
            "status IN ('NEW', 'READ', 'REPLIED', 'ARCHIVED')",
            name="ck_contact_requests_status",
        ),
        sa.ForeignKeyConstraint(
            ["interested_service_line_id"],
            ["service_lines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contact_requests_created_at"),
        "contact_requests",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contact_requests_email"), "contact_requests", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_contact_requests_interested_service_line_id"),
        "contact_requests",
        ["interested_service_line_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contact_requests_status"), "contact_requests", ["status"], unique=False
    )
    op.create_table(
        "projects",
        sa.Column("slug", sa.String(length=150), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("short_description", sa.Text(), nullable=True),
        sa.Column("full_description", sa.Text(), nullable=True),
        sa.Column("repository_url", sa.Text(), nullable=True),
        sa.Column("live_demo_url", sa.Text(), nullable=True),
        sa.Column("cover_image", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("visibility", sa.String(length=50), nullable=False),
        sa.Column("featured", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.Date(), nullable=True),
        sa.Column("finished_at", sa.Date(), nullable=True),
        sa.Column("client_id", GUID(), nullable=True),
        sa.Column("id", GUID(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('PLANNING', 'IN_PROGRESS', 'COMPLETED', 'ARCHIVED')",
            name="ck_projects_status",
        ),
        sa.CheckConstraint(
            "visibility IN ('PUBLIC', 'PRIVATE')", name="ck_projects_visibility"
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(
        op.f("ix_projects_client_id"), "projects", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_projects_featured"), "projects", ["featured"], unique=False
    )
    op.create_index(op.f("ix_projects_status"), "projects", ["status"], unique=False)
    op.create_index(op.f("ix_projects_title"), "projects", ["title"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", GUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("issued_at", UTCDateTime(), nullable=False),
        sa.Column("expires_at", UTCDateTime(), nullable=False),
        sa.Column("revoked_at", UTCDateTime(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("id", GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_expires_at"),
        "refresh_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "services",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("featured", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("service_line_id", GUID(), nullable=True),
        sa.Column("id", GUID(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_line_id"],
            ["service_lines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(
        op.f("ix_services_service_line_id"),
        "services",
        ["service_line_id"],
        unique=False,
    )
    op.create_table(
        "team_members",
        sa.Column("user_id", GUID(), nullable=True),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("role", sa.String(length=150), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("photo", sa.Text(), nullable=True),
        sa.Column("linkedin_url", sa.Text(), nullable=True),
        sa.Column("github_url", sa.Text(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", GUID(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_team_members_active"), "team_members", ["active"], unique=False
    )
    op.create_index(
        op.f("ix_team_members_user_id"), "team_members", ["user_id"], unique=False
    )
    op.create_table(
        "article_technologies",
        sa.Column("article_id", GUID(), nullable=False),
        sa.Column("technology_id", GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["technology_id"],
            ["technologies.id"],
        ),
        sa.PrimaryKeyConstraint("article_id", "technology_id"),
    )
    op.create_table(
        "case_studies",
        sa.Column("project_id", GUID(), nullable=False),
        sa.Column("challenge", sa.Text(), nullable=True),
        sa.Column("solution", sa.Text(), nullable=True),
        sa.Column("architecture", sa.Text(), nullable=True),
        sa.Column("lessons_learned", sa.Text(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("id", GUID(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project_technologies",
        sa.Column("project_id", GUID(), nullable=False),
        sa.Column("technology_id", GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["technology_id"],
            ["technologies.id"],
        ),
        sa.PrimaryKeyConstraint("project_id", "technology_id"),
    )
    op.create_table(
        "testimonials",
        sa.Column("author_name", sa.String(length=150), nullable=False),
        sa.Column("author_role", sa.String(length=150), nullable=True),
        sa.Column("client_id", GUID(), nullable=True),
        sa.Column("project_id", GUID(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("rating", sa.SmallInteger(), nullable=True),
        sa.Column("featured", sa.Boolean(), nullable=False),
        sa.Column("id", GUID(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "rating IS NULL OR rating BETWEEN 1 AND 5",
            name="ck_testimonials_rating_range",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_testimonials_client_id"), "testimonials", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_testimonials_featured"), "testimonials", ["featured"], unique=False
    )
    op.create_index(
        op.f("ix_testimonials_project_id"), "testimonials", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Autogenerate emits an explicit op.drop_index() immediately before each
    # op.drop_table() for that same table — redundant (DROP TABLE already
    # removes its indexes) and actively broken on MySQL for any index
    # backing a foreign key: MySQL refuses to drop such an index while the
    # FK constraint still exists (error 1553 "needed in a foreign key
    # constraint"), unlike Postgres which has no such ordering requirement.
    # Table drop order below is unchanged from autogenerate (reverse FK
    # dependency order) — only the redundant drop_index() calls are removed.
    op.drop_table("testimonials")
    op.drop_table("project_technologies")
    op.drop_table("case_studies")
    op.drop_table("article_technologies")
    op.drop_table("team_members")
    op.drop_table("services")
    op.drop_table("refresh_tokens")
    op.drop_table("projects")
    op.drop_table("contact_requests")
    op.drop_table("articles")
    op.drop_table("users")
    op.drop_table("technologies")
    op.drop_table("service_lines")
    op.drop_table("products")
    op.drop_table("partners")
    op.drop_table("companies")
    op.drop_table("clients")
